### ISSUE TITLE
Number of connections limited to ~5000 ?

### ISSUE THREAD

**Issue by StefH** [bryceg/Owin.WebSocket#10]
When using a Web Socket client (https://github.com/StefH/WebSocketTest), I can only get around 5000 web socket connections on IIS Express?

Is there a setting in web.config or in Owin.WebSocket which I need to modify ?

**Comment by bryceg** [comment]
I believe this is a setting in aspnet config.
http://stackoverflow.com/questions/11667799/while-using-signalr-will-there-be-any-connection-limits-on-iis

**Comment by StefH** [comment]
Indeed, in that post they observer the same issue:
Here are my findings. ASP.NET 4.0 by default accepts 5000 maximum concurrent requests per CPU. To change this we need to set this number in ASP.NET Config file which can be found in this location %windir%\Microsoft.NET\Framework\v4.0.30319\aspnet.config

However, I have 4 CPUs defined in my Virtual Machine, so would expect different result if it's 5000 per CPU.
