### ISSUE TITLE
Tagging in source tree to match NuGet package release

### ISSUE THREAD

**Issue by f-camera** [bryceg/Owin.WebSocket#18]
Could you please provide tagging/branching on the source repository so that it's easier to find out what are the sources exactly matching the released NuGet package version?
Or even be able to read it on [Releases] (https://github.com/bryceg/Owin.WebSocket/releases) page.

Should I assume that package version [1.5.0] (https://www.nuget.org/packages/Owin.WebSocket/1.5.0) is corresponding to the current HEAD (revision 9809a1898ae894d1110047911e30119a2ce4c598 )?

Thanks in advance.

**Comment by bryceg** [comment]
Yes, you can assume 1.5.0 is that revision.

I'll do this going forward though.
