### ISSUE TITLE
All public methods which return a Task should be named ***Async

### ISSUE THREAD

**Issue by StefH** [bryceg/Owin.WebSocket#9]
See also this question and answer on SO: http://stackoverflow.com/questions/15951774/naming-convention-for-async-methods

**Comment by graphnode** [comment]
Unless, and I quote, 
> Of course, there are always exceptions to a guideline. The most notable one in the case of naming would be cases where an entire type’s raison d’etre is to provide async-focused functionality, in which case having Async on every method would be overkill, e.g. the methods on Task itself that produce other Tasks.

From the code I can see that ***Async naming pattern is used as a way to distinguish between synchronous and asynchronous methods and is not used when there are no synchronous methods available.
